title: Triadic Wizards
description: A mythic-scientific lattice for reproducible resonance
theme: jekyll-theme-hacker
url: "https://los.triadicwizards.win"
baseurl: ""  # Leave blank since you're using a custom domain
