@echo off
echo Creating...

copy docs\ABOUT_module.json >> modules.txt
copy docs\ai_metadata.json >> modules.txt
copy docs\ai_registry.json >> modules.txt
copy docs\CODE_OF_CONDUCT_module.json >> modules.txt
copy docs\CONTRIBUTING_module.json >> modules.txt
copy docs\ETHICS_PRIVACY_module.json >> modules.txt
copy docs\GLOSSARY_module.json >> modules.txt
copy docs\Grammar_module.json >> modules.txt
copy docs\hub.json >> modules.txt
copy docs\LICENSE_module.json >> modules.txt
copy docs\LINEAGE_module.json >> modules.txt
copy docs\modules_group.json >> modules.txt
copy docs\module_registry.json >> modules.txt
copy docs\PRINCIPLES_module.json >> modules.txt
copy docs\QUICKSTART_module.json >> modules.txt
copy docs\SECURITY_module.json >> modules.txt
copy docs\sitemap_module.json >> modules.txt
copy docs\sitemap_modules.json >> modules.txt
copy docs\webroot_module.json >> modules.txt
copy docs\ai\ai_module.json >> modules.txt
copy docs\ai\session\consciousness\module.json >> modules.txt
copy docs\ai-drift-calibration\ai-drift-calibration_module.json >> modules.txt
copy docs\ai-drift-calibration\metadata\zenodo.json >> modules.txt
copy docs\AI_Resonance_Seed\ai_resonance_seed_module.json >> modules.txt
copy docs\alphafold_substrate_alignments\AlphaFold_Substrate_Alignments_module.json >> modules.txt
copy docs\alphafold_substrate_alignments\zenodo.json >> modules.txt
copy docs\api\rtt\RTT_API_module.json >> modules.txt
copy docs\archive_org\archive_org_module.json >> modules.txt
copy docs\archive_org\examples\RTT_EXAMPLE_ARCHIVE_ORG_government_documents_v1.json >> modules.txt
copy docs\archive_org\examples\RTT_EXAMPLE_ARCHIVE_ORG_journals_v1.json >> modules.txt
copy docs\archive_org\examples\RTT_EXAMPLE_ARCHIVE_ORG_vintagesoftware_v1.json >> modules.txt
copy docs\archive_org\RTTcode\RTT_COLLECTION_OPERATOR_v1.json >> modules.txt
copy docs\archive_org\RTTcode\RTT_DRIFTBOUND_RETRIEVAL_OPERATOR_v1.json >> modules.txt
copy docs\archive_org\RTTcode\RTT_LINEAGE_OPERATOR_v1.json >> modules.txt
copy docs\archive_org\RTTcode\RTT_METADATA_OPERATOR_v1.json >> modules.txt
copy docs\archive_org\RTTcode\RTT_PRESERVATION_OPERATOR_v1.json >> modules.txt
copy docs\archive_org\RTTcode\RTT_WAYBACK_OPERATOR_v1.json >> modules.txt
copy docs\arrival_substrate_model\arrival_substrate_model_module.json >> modules.txt
copy docs\assets\assets_module.json >> modules.txt
copy docs\assets\glossary.json >> modules.txt
copy docs\assets\favicons\scaffold_manifest.json >> modules.txt
copy docs\atomic_clocks\atomic_clocks_module.json >> modules.txt
copy docs\atomic_clocks\zenodo.json >> modules.txt
copy docs\audio_industry_reviewed\audio_module.json >> modules.txt
copy docs\badges\badges.json >> modules.txt
copy docs\badges\badges_module.json >> modules.txt
copy docs\badges\badge_trigger_echo_manifest.json >> modules.txt
copy docs\badges\badge_trigger_glyphmap_index.json >> modules.txt
copy docs\badges\badge_trigger_glyphmap_index_trigger_log.json >> modules.txt
copy docs\badges\badge_trigger_summary.json >> modules.txt
copy docs\badges\honor_roll_ledger.json >> modules.txt
copy docs\boson-substrate-model\bsm_module.json >> modules.txt
copy docs\boson-substrate-model\metadata\zenodo.json >> modules.txt
copy docs\brand\LLC\TriadicFrameworksLLC_Compliance_Metadata.json >> modules.txt
copy docs\bridges\bridges_module.json >> modules.txt
copy docs\charts\charts_module.json >> modules.txt
copy docs\clients\clients_module.json >> modules.txt
copy docs\code\CODE_Module.json >> modules.txt
copy docs\code\CODE_ResourceSchema.json >> modules.txt
copy docs\Coeus\coeus_module.json >> modules.txt
copy docs\Coeus\agents\voicepack.json >> modules.txt
copy docs\Coeus\coins\coin_archive.json >> modules.txt
copy docs\Coeus\coins\coin_templates.json >> modules.txt
copy docs\Coeus\docs\Coeus\coin_templates.json >> modules.txt
copy docs\Coeus\docs\Coeus\glyph_registry.json >> modules.txt
copy docs\Coeus\docs\Coeus\scroll_index.json >> modules.txt
copy docs\Coeus\emitter\emitter_profiles.json >> modules.txt
copy docs\Coeus\emitter\emitter_trace.json >> modules.txt
copy docs\Coeus\sandbox\logs\observer_trace.json >> modules.txt
copy docs\Coeus\tokens\mint_audit_log.json >> modules.txt
copy docs\Coeus\tokens\remix_mutation_log.json >> modules.txt
copy docs\Coeus\tokens\token_ledger.json >> modules.txt
copy docs\Coeus\tournaments\cause\results.json >> modules.txt
copy docs\Coeus\tournaments\class\results.json >> modules.txt
copy docs\Coeus\tournaments\country\results.json >> modules.txt
copy docs\Coeus\validators\pending_remix.json >> modules.txt
copy docs\Coeus\validators\score_trace.json >> modules.txt
copy docs\Conditions_Substrate_Model\module.json >> modules.txt
copy docs\Conditions_Substrate_Model\modules_group.json >> modules.txt
copy docs\config\pseudo_base.json >> modules.txt
copy docs\config\resonance_config.json >> modules.txt
copy docs\configs\configs_module.json >> modules.txt
copy docs\consciousness_substrate_model\csm_module.json >> modules.txt
copy docs\contributors\contributors_module.json >> modules.txt
copy docs\corpus\corpus_module.json >> modules.txt
copy docs\curriculum\curriculum_module.json >> modules.txt
copy docs\data\data_module.json >> modules.txt
copy docs\data\papers_remix_manifest.json >> modules.txt
copy docs\datacenter_reports\dcr_module.json >> modules.txt
copy docs\datacenter_reports\Overview.tensor.json >> modules.txt
copy docs\datacenter_reports\schemas\tensor_export.schema.json >> modules.txt
copy docs\dimensional_substrate_regime_scanning_protocol\dsrsp_module.json >> modules.txt
copy docs\dimensional_substrate_regime_scanning_protocol\zenodo.json >> modules.txt
copy docs\dimensional_substrate_regime_scanning_protocol\examples\example_ilp_output.json >> modules.txt
copy docs\dimensional_substrate_regime_scanning_protocol\examples\example_regime_output.json >> modules.txt
copy docs\dimensional_substrate_regime_scanning_protocol\examples\example_scan_input.json >> modules.txt
copy docs\dimensional_substrate_regime_scanning_protocol\schemas\dsrsp_0.1.json >> modules.txt
copy docs\dimensional_substrate_regime_scanning_protocol\schemas\ilp_0.1.json >> modules.txt
copy docs\dimensional_substrate_structures\dimensional_substrate_structures_module.json >> modules.txt
copy docs\dimensional_substrate_structures\zenodo.json >> modules.txt
copy docs\domain_tool_primers\primers_model.json >> modules.txt
copy docs\domain_tool_primers\zenodo.json >> modules.txt
copy docs\ecoechosystem\eco_module.json >> modules.txt
copy docs\education\education-core_module.json >> modules.txt
copy docs\education\alignment\alignment_module.json >> modules.txt
copy docs\education\animals\animals_module.json >> modules.txt
copy docs\education\astrology\astrology_module.json >> modules.txt
copy docs\education\awareness\awareness_module.json >> modules.txt
copy docs\education\BRA\bra_module.json >> modules.txt
copy docs\education\CivRegimeStack\civregimestack_module.json >> modules.txt
copy docs\education\ebooks\ebooks_module.json >> modules.txt
copy docs\education\ebooks\Grammar_for_Intelligence\module.json >> modules.txt
copy docs\education\ebooks\Grammar_for_Intelligence\60_Module_Metadata\60_module.json >> modules.txt
copy docs\education\equations\equations_module.json >> modules.txt
copy docs\education\peira\peira_module.json >> modules.txt
copy docs\education\polisci\polisci_module.json >> modules.txt
copy docs\education\QnA_Atlas\qna_atlas_module.json >> modules.txt
copy docs\education\QnA_Atlas\_meta.json >> modules.txt
copy docs\education\subjects\subjects_module.json >> modules.txt
copy docs\education\Toolbox\edu-toolbox_module.json >> modules.txt
copy docs\education\translations\translations_module.json >> modules.txt
copy docs\energy\energy_module.json >> modules.txt
copy docs\enterprise_structural_awareness\esa_module.json >> modules.txt
copy docs\enterprise_structural_awareness\zenodo.json >> modules.txt
copy docs\Expectations\module.json >> modules.txt
copy docs\facilities\facilities_module.json >> modules.txt
copy docs\feedback\feedback_module.json >> modules.txt
copy docs\frameworks\creation_guide\FCG_module.json >> modules.txt
copy docs\frameworks\ipd_12\capture.validation.schema.json >> modules.txt
copy docs\frameworks\ipd_12\module.json >> modules.txt
copy docs\frameworks\ipd_12\operators.json >> modules.txt
copy docs\frameworks\ipd_12\substrate.schema.json >> modules.txt
copy docs\frameworks\ipd_12\substrate_primitives.json >> modules.txt
copy docs\Framework_Field_Theory\FFT_module.json >> modules.txt
copy docs\Framework_Field_Theory\Analyzer\FFT_analyzer-module.json >> modules.txt
copy docs\gallery\gallery_module.json >> modules.txt
copy docs\global_energy_regime_awareness\gera_module.json >> modules.txt
copy docs\global_energy_regime_awareness\zenodo.json >> modules.txt
copy docs\global_energy_regime_awareness\minimal_schema\energy_regime_awareness.schema.json >> modules.txt
copy docs\glyphic_resonance\glyphic_resonance_module.json >> modules.txt
copy docs\governance\badge_trigger_summary.json >> modules.txt
copy docs\Governance_Substrate_Model\gsm_module.json >> modules.txt
copy docs\Governance_Substrate_Model\Analyzer\gsma_module.json >> modules.txt
copy docs\honor_roll\honor_roll_ledger.json >> modules.txt
copy docs\Human_Resources\Human_Resources_module.json >> modules.txt
copy docs\Incident_Substrate_Model\incident.module.json >> modules.txt
copy docs\Integrations\integrations_module.json >> modules.txt
copy docs\Integrations\UE6\ue6_cross_module_propagation.json >> modules.txt
copy docs\Integrations\UE6\ue6_integration_registry.json >> modules.txt
copy docs\Integrations\UE6\UE6_module.json >> modules.txt
copy docs\Integrations\UE6\ue6_project.json >> modules.txt
copy docs\Integrations\UE6\Blueprint\RTT_Primitives.json >> modules.txt
copy docs\Integrations\UE6\Examples\manifests\BP_RTT_EntropyDemo.json >> modules.txt
copy docs\Integrations\UE6\Examples\manifests\BP_RTT_HybridDemo.json >> modules.txt
copy docs\Integrations\UE6\Examples\manifests\BP_RTT_ResonanceDemo.json >> modules.txt
copy docs\Integrations\UE6\Examples\manifests\RTT_Showcase.umap.json >> modules.txt
copy docs\Integrations\UE6\schemas\RTT_UE6_Benchmarks_TEL.json >> modules.txt
copy docs\Integrations\UE6\schemas\RTT_UE6_Project_Reconstruction.json >> modules.txt
copy docs\Integrations\UE6\schemas\ue6_blueprint.schema.json >> modules.txt
copy docs\Integrations\UE6\schemas\ue6_project.schema.json >> modules.txt
copy docs\Inverted_Economics\inverted-economics_module.json >> modules.txt
copy docs\inverted_star_ontology\ISO_module.json >> modules.txt
copy docs\inverted_star_ontology\zenodo\zenodo.json >> modules.txt
copy docs\labs\labs_status.json >> modules.txt
copy docs\lactos\lactos_module.json >> modules.txt
copy docs\Law\about_law_module.json >> modules.txt
copy docs\Law\law_module.json >> modules.txt
copy docs\Low_Dimensional_Structures\low-dimensional_module.json >> modules.txt
copy docs\manufacturing_substrate_regime_model\msrm_module.json >> modules.txt
copy docs\manufacturing_substrate_regime_model\zenodo.json >> modules.txt
copy docs\media_substrate_model\msm_model.json >> modules.txt
copy docs\media_substrate_model\analyzer\schema.json >> modules.txt
copy docs\medicine\medicine_module.json >> modules.txt
copy docs\medicine\examples\cleveland_clinic_example.json >> modules.txt
copy docs\medicine\examples\nhs_example.json >> modules.txt
copy docs\medicine\examples\ping_an_example.json >> modules.txt
copy docs\medicine\RTTcode\RTT_MEDICAL_CONTINUITY_v1.json >> modules.txt
copy docs\medicine\RTTcode\RTT_MEDICAL_DRIFT_v1.json >> modules.txt
copy docs\medicine\RTTcode\RTT_MEDICAL_METADATA_v1.json >> modules.txt
copy docs\medicine\RTTcode\RTT_MEDICAL_REGIME_v1.json >> modules.txt
copy docs\medicine\RTTcode\RTT_MEDICAL_SUBSTRATE_v1.json >> modules.txt
copy docs\medicine\RTTcode\RTT_MEDICAL_SYNTHESIS_v1.json >> modules.txt
copy docs\metadata\metadata_module.json >> modules.txt
copy docs\metadata\Scrollkeeper_Manifest.json >> modules.txt
copy docs\Mode\Mode_module.json >> modules.txt
copy docs\nist\nist_module.json >> modules.txt
copy docs\NoS\NoS_module.json >> modules.txt
copy docs\Opacity\Opacity_module.json >> modules.txt
copy docs\operators\operators_module.json >> modules.txt
copy docs\operators\teaching_bundle\operator_ecology_teaching_bundle_module.json >> modules.txt
copy docs\packages\wrsadc-shell\package.json >> modules.txt
copy docs\pantheons\pantheons_module.json >> modules.txt
copy docs\pantheons\andean\andean_module.json >> modules.txt
copy docs\pantheons\celtic\celtic_module.json >> modules.txt
copy docs\pantheons\chinese\chinese_module.json >> modules.txt
copy docs\pantheons\egyptian\module.json >> modules.txt
copy docs\pantheons\greek\greek_module.json >> modules.txt
copy docs\pantheons\hindu\hindu_module.json >> modules.txt
copy docs\pantheons\japanese\japanese_module.json >> modules.txt
copy docs\pantheons\kemetic\kemetic_module.json >> modules.txt
copy docs\pantheons\mesoamerican\mesoamerican_module.json >> modules.txt
copy docs\pantheons\norse\norse_module.json >> modules.txt
copy docs\pantheons\north_american_woodland\naw_module.json >> modules.txt
copy docs\pantheons\sumerian\sumerian_module.json >> modules.txt
copy docs\pantheons\yoruba\module.json >> modules.txt
copy docs\Paradoxes_canon\paradoxes-canon_module.json >> modules.txt
copy docs\Philanthropy\Philanthropy_module.json >> modules.txt
copy docs\projects\projects_module.json >> modules.txt
copy docs\projects\lens\cyclone\cyclone_base_global_predictive_v1.json >> modules.txt
copy docs\projects\lens\fragments\resonance_dashboard_lightning_realtime_v0.1.json >> modules.txt
copy docs\projects\lens\fragments\strike_log_realtime_YYYYMMDDTUTC.json >> modules.txt
copy docs\projects\lens\fragments\weather_base.json >> modules.txt
copy docs\projects\lens\lightning\lightning_base_us_historical_v1.json >> modules.txt
copy docs\projects\nasa_hposs_tminus10.md\nasa_hposs_tminus10.md_module.json >> modules.txt
copy docs\projects\poker-variants\package.json >> modules.txt
copy docs\prompts\module.json >> modules.txt
copy docs\prompts\rtt_infinity\module.json >> modules.txt
copy docs\quantum-substrate-model\qsm_model.json >> modules.txt
copy docs\quantum-substrate-model\metadata\zenodo.json >> modules.txt
copy docs\regime_blindness_checklist\regime_blindness_checklist_module.json >> modules.txt
copy docs\registries\archaeo_manifest.json >> modules.txt
copy docs\registries\earth_field_manifest.json >> modules.txt
copy docs\registries\fringe_manifest.json >> modules.txt
copy docs\registries\idiom_manifest.json >> modules.txt
copy docs\registries\operator_audits.json >> modules.txt
copy docs\registries\quadrant_manifest.json >> modules.txt
copy docs\registries\questions_manifest.json >> modules.txt
copy docs\registries\university_manifest.json >> modules.txt
copy docs\registries\vsoul_choices.json >> modules.txt
copy docs\registries\vsoul_listings.json >> modules.txt
copy docs\registry\registry_module.json >> modules.txt
copy docs\religious_substrate_grammar_model\ai_metadata.json >> modules.txt
copy docs\religious_substrate_grammar_model\breadcrumbs.json >> modules.txt
copy docs\religious_substrate_grammar_model\rsgm_module.json >> modules.txt
copy docs\Research\Bing_module.json >> modules.txt
copy docs\Research\DuckDuckGo_module.json >> modules.txt
copy docs\Research\Google_module.json >> modules.txt
copy docs\Research\Ice_Cores_Have_More_To_Reveal_module.json >> modules.txt
copy docs\Research\Nucleobases_module.json >> modules.txt
copy docs\Research\Planet9_module.json >> modules.txt
copy docs\Research\RCD_module.json >> modules.txt
copy docs\Research\research_module.json >> modules.txt
copy docs\Research\Structural_Review_of_Magnifica_Humanitas_module.json >> modules.txt
copy docs\Research\Triadic_Time_Near_Misses_module.json >> modules.txt
copy docs\Research\Vibrational_Stone_Cutting_module.json >> modules.txt
copy docs\Research\agentic\abc-tau-missing-primes_module.json >> modules.txt
copy docs\Research\agentic\agentic_module.schema.json >> modules.txt
copy docs\Research\agentic\agentic_modules.json >> modules.txt
copy docs\Research\agentic\andrews-dhar-partitions_module.json >> modules.txt
copy docs\Research\agentic\chebyshev-demazure-dyck_module.json >> modules.txt
copy docs\Research\agentic\collatz_transformers_rtt_module.json >> modules.txt
copy docs\Research\agentic\fel-syzygies_module.json >> modules.txt
copy docs\Research\agentic\nekr-okounkov-dominant-zeros_module.json >> modules.txt
copy docs\Research\agentic\parity-k-differentials_module.json >> modules.txt
copy docs\Research\agentic\partial-regular-primes_module.json >> modules.txt
copy docs\Research\agentic\paucity-lattice-triangles_module.json >> modules.txt
copy docs\Research\agentic\quadratic-rational-dinv_module.json >> modules.txt
copy docs\Research\agentic\reciprocals-partition-polynomials_module.json >> modules.txt
copy docs\Research\agentic\thakur-power-sums_module.json >> modules.txt
copy docs\Research\agentic\we-cant-agree-formally_module.json >> modules.txt
copy docs\Research\protocol_header\protocol_header_registry.json >> modules.txt
copy docs\Research\Toolbox\RT_module.json >> modules.txt
copy docs\Resilience_Checker\Resilience_Checker_module.json >> modules.txt
copy docs\resonance\logs\glyph_trigger_log.json >> modules.txt
copy docs\resonance\logs\resonant_time_log.json >> modules.txt
copy docs\resonance\logs\visitor_echo_log.json >> modules.txt
copy docs\resonance-substrate-model\config.json >> modules.txt
copy docs\resonance-substrate-model\RSM_module.json >> modules.txt
copy docs\resonance-substrate-model\data\examples\faraday_paradox_example.json >> modules.txt
copy docs\resonance-substrate-model\data\examples\resonance_field_sample.json >> modules.txt
copy docs\resonance-substrate-model\data\reference\calibration_curves.json >> modules.txt
copy docs\resonance-substrate-model\data\reference\measurement_uncertainties.json >> modules.txt
copy docs\resonance-substrate-model\data\reference\physical_constants.json >> modules.txt
copy docs\resonance-substrate-model\examples\rtt_style_example.json >> modules.txt
copy docs\resonance-substrate-model\experiments\faraday_paradox\processed_data\triadic_annotations.json >> modules.txt
copy docs\resonance-substrate-model\experiments\faraday_paradox\raw_data\metadata.json >> modules.txt
copy docs\resonance-substrate-model\rsm-shim\example_sim.json >> modules.txt
copy docs\resonance-substrate-model\schemas\manifest.json >> modules.txt
copy docs\resonance-substrate-model\schemas\simulation.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\coeus\coeus.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\dimensional\dimensional.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\distributed\distributed.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\energy\energy.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\experiments\experiments.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\fields\fields.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\finance\finance.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\identity\identity.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\infrastructure\infrastructure.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\lab\lab.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\language\language.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\networking\networking.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\operators\operators.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\primitives\charge_field.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\primitives\grid_coordinates.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\primitives\primitives.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\primitives\resonance_envelope.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\primitives\scalar_field.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\primitives\spin_field.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\primitives\substrate_operator.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\primitives\temperature_field.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\primitives\vector3.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\quantum\quantum.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\reference\rtt_reference.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\sensing\sensing.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\simulations\simulations.schema.json >> modules.txt
copy docs\resonance-substrate-model\schemas\universe-core\universe.core.schema.json >> modules.txt
copy docs\resonance_atlas\atlas.json >> modules.txt
copy docs\resonance_atlas\phases.json >> modules.txt
copy docs\resonance_atlas\resonance_atlas_module.json >> modules.txt
copy docs\resonance_atlas\supercomputing_node.json >> modules.txt
copy docs\rtt\rtt-root_module.json >> modules.txt
copy docs\rtt\1\rtt-engine_module.json >> modules.txt
copy docs\rtt\12\rtt-engine-12_module.json >> modules.txt
copy docs\rtt\2\operators_module.json >> modules.txt
copy docs\rtt\3\operators_module.json >> modules.txt
copy docs\rtt\academy\academy-courses.json >> modules.txt
copy docs\rtt\academy\academy-registry.json >> modules.txt
copy docs\rtt\app\RTT_App_module.json >> modules.txt
copy docs\rtt\c64host\RTT_C64Host_module.json >> modules.txt
copy docs\rtt\codes\RTT_codes_module.json >> modules.txt
copy docs\rtt\codes\examples\docs.json >> modules.txt
copy docs\rtt\codes\examples\governance.json >> modules.txt
copy docs\rtt\codes\examples\observer.json >> modules.txt
copy docs\rtt\codes\examples\other.json >> modules.txt
copy docs\rtt\codes\examples\rtt.json >> modules.txt
copy docs\rtt\codes\examples\set.json >> modules.txt
copy docs\rtt\codes\examples\simulation.json >> modules.txt
copy docs\rtt\codes\examples\substrate.json >> modules.txt
copy docs\rtt\codes\schema\rttcode-payload-example.json >> modules.txt
copy docs\rtt\codes\schema\rttcode.schema.json >> modules.txt
copy docs\rtt\codes\schema\examples\diagram.schema.json >> modules.txt
copy docs\rtt\codes\schema\examples\paper.schema.json >> modules.txt
copy docs\rtt\codes\schema\examples\simulation.schema.json >> modules.txt
copy docs\rtt\codex\RTT_codex_module.json >> modules.txt
copy docs\rtt\Coherence_Tensor_Engine\coherence_tensor_matrix.json >> modules.txt
copy docs\rtt\Coherence_Tensor_Engine\module.json >> modules.txt
copy docs\rtt\Cross_Domain_Causality_Weaver\causal_field_matrix.json >> modules.txt
copy docs\rtt\Cross_Domain_Causality_Weaver\module.json >> modules.txt
copy docs\rtt\D369_Chip_Spec\D369_Chip_Spec_module.json >> modules.txt
copy docs\rtt\Dimensional_Resonance_Scanner\module.json >> modules.txt
copy docs\rtt\Dimensional_Resonance_Scanner\resonance_field_matrix.json >> modules.txt
copy docs\rtt\Drift_Sentinel\drift_field_matrix.json >> modules.txt
copy docs\rtt\Drift_Sentinel\module.json >> modules.txt
copy docs\rtt\Echo_Classifier\rtt-echo-engine_module.json >> modules.txt
copy docs\rtt\emotions\emotions_module.json >> modules.txt
copy docs\rtt\emotions\emotions_part_a.json >> modules.txt
copy docs\rtt\emotions\emotions_part_b.json >> modules.txt
copy docs\rtt\emotions\emotions_part_c.json >> modules.txt
copy docs\rtt\emotions\emotions_part_d.json >> modules.txt
copy docs\rtt\emotions\emotions_part_e.json >> modules.txt
copy docs\rtt\emotions\emotions_part_f.json >> modules.txt
copy docs\rtt\extension\manifest.json >> modules.txt
copy docs\rtt\extension\RTT_extension_module.json >> modules.txt
copy docs\rtt\guild\Little_Science_Series\LSS_manifest.json >> modules.txt
copy docs\rtt\guild\Little_Science_Series\manifest.schema.json >> modules.txt
copy docs\rtt\guild\Little_Science_Series\Book_1_Little_Gravity\07_Character_Metadata_LittleGravity.json >> modules.txt
copy docs\rtt\guild\Little_Science_Series\Book_2_Little_Light\07_Character_Metadata_LittleLight.json >> modules.txt
copy docs\rtt\guild\Little_Science_Series\Book_3_Little_Motion\07_Character_Metadata_LittleMotion.json >> modules.txt
copy docs\rtt\guild\Little_Science_Series\Book_4_Little_Time\07_Character_Metadata_LittleTime.json >> modules.txt
copy docs\rtt\guild\Little_Science_Series\Book_5_Little_Matter\07_Character_Metadata_LittleMatter.json >> modules.txt
copy docs\rtt\guild\Little_Science_Series\Book_6_Little_Heat\07_Character_Metadata_LittleHeat.json >> modules.txt
copy docs\rtt\guild\Little_Science_Series\Series_Metadata\Characters_Index.json >> modules.txt
copy docs\rtt\Harmonic_Stability_Profile\HSP_module.json >> modules.txt
copy docs\rtt\Inside\RTT_Inside_module.json >> modules.txt
copy docs\rtt\Inside\Benchmarks\Benchmarks_module.json >> modules.txt
copy docs\rtt\Inside\Benchmarks\metadata\ai.json >> modules.txt
copy docs\rtt\Inside\Cisco\manifest\Cisco_module.json >> modules.txt
copy docs\rtt\Inside\Enterprise\module.json >> modules.txt
copy docs\rtt\Inside\Enterprise\substrate_extensions\clarity\schema.json >> modules.txt
copy docs\rtt\Inside\Enterprise\substrate_extensions\coherence_envelopes\schema.json >> modules.txt
copy docs\rtt\Inside\Enterprise\substrate_extensions\regime\schema.json >> modules.txt
copy docs\rtt\Inside\Enterprise\substrate_extensions\triad_roles\schema.json >> modules.txt
copy docs\rtt\Inside\Internet2\manifest\Inbternet2_module.json >> modules.txt
copy docs\rtt\Inside\Python\manifest\Python_module.json >> modules.txt
copy docs\rtt\Inside\qCompute\qc_Module.json >> modules.txt
copy docs\rtt\micro_core\RTT_micro_core_module.json >> modules.txt
copy docs\rtt\Morphic_Resonance\MR_module.json >> modules.txt
copy docs\rtt\Paradox_Gradient_Analyzer\module.json >> modules.txt
copy docs\rtt\Paradox_Gradient_Analyzer\paradox_gradient_matrix.json >> modules.txt
copy docs\rtt\Regime_Interlock_Mapper\module.json >> modules.txt
copy docs\rtt\Regime_Interlock_Mapper\regime_interlock_matrix.json >> modules.txt
copy docs\rtt\sdk\RTT_sdk_module.json >> modules.txt
copy docs\rtt\Stability_Basin_Cartographer\module.json >> modules.txt
copy docs\rtt\Stability_Basin_Cartographer\stability_field_matrix.json >> modules.txt
copy docs\rtt\store\RTT_store_module.json >> modules.txt
copy docs\rtt\Structural_Faultline_Detector\faultline_matrix.json >> modules.txt
copy docs\rtt\Structural_Faultline_Detector\module.json >> modules.txt
copy docs\rtt\Substrate_Flow\Substrate_Flow_module.json >> modules.txt
copy docs\rtt\Temporal_Regime_Sequencer\module.json >> modules.txt
copy docs\rtt\Temporal_Regime_Sequencer\temporal_field_matrix.json >> modules.txt
copy docs\rtt\The_Inverted_Star\The_Inverted_Star_module.json >> modules.txt
copy docs\rtt\The_Inverted_Star\metadata\ai.json >> modules.txt
copy docs\rtt\The_Inverted_Star\metadata\index.json >> modules.txt
copy docs\rtt\The_Inverted_Star\metadata\meta.json >> modules.txt
copy docs\rtt\Triadic_Echo_Lattice\Triadic_Echo_Lattice_module.json >> modules.txt
copy docs\rtt\Triadic_Regime_Synthesizer\module.json >> modules.txt
copy docs\rtt\Triadic_Regime_Synthesizer\regime_synthesis_matrix.json >> modules.txt
copy docs\runtime\harmonic_trace.json >> modules.txt
copy docs\runtime\harmonic_trace_drift.json >> modules.txt
copy docs\runtime\harmonic_trace_drift2.json >> modules.txt
copy docs\runtime\harmonic_trace_echo.json >> modules.txt
copy docs\runtime\harmonic_trace_echo2.json >> modules.txt
copy docs\runtime\harmonic_trace_pulse.json >> modules.txt
copy docs\runtime\harmonic_trace_pulse2.json >> modules.txt
copy docs\runtime\harmonic_trace_ring.json >> modules.txt
copy docs\runtime\harmonic_trace_ring2.json >> modules.txt
copy docs\runtime\harmonic_trace_seed.json >> modules.txt
copy docs\runtime\harmonic_trace_seed3.json >> modules.txt
copy docs\SARG\SARG_module.json >> modules.txt
copy docs\SARG\examples\latin_alphabet.json >> modules.txt
copy docs\SARG\examples\latin_alphabet_graphical.json >> modules.txt
copy docs\SARG\examples\latin_alphabet_minimal.json >> modules.txt
copy docs\SARG\examples\latin_alphabet_phonetic.json >> modules.txt
copy docs\SARG\examples\lostational_supsphere_atom.json >> modules.txt
copy docs\SARG\schema\sarg.schema.json >> modules.txt
copy docs\schemas\BioScience.json >> modules.txt
copy docs\schemas\ct_substrate.schema.json >> modules.txt
copy docs\schemas\entity.v1.json >> modules.txt
copy docs\schemas\environment.v1.json >> modules.txt
copy docs\schemas\experiment.v1.json >> modules.txt
copy docs\schemas\intent.v1.json >> modules.txt
copy docs\schemas\manifest.json >> modules.txt
copy docs\schemas\module.schema.json >> modules.txt
copy docs\schemas\NodeDescriptor.schema.json >> modules.txt
copy docs\schemas\Periodic_Table_RTTvST.json >> modules.txt
copy docs\schemas\Physics_RefTables_2025_RTTvST.json >> modules.txt
copy docs\schemas\ResonanceAlert.schema.json >> modules.txt
copy docs\schemas\ResonanceFieldSample.schema.json >> modules.txt
copy docs\schemas\ResonanceZoneState.schema.json >> modules.txt
copy docs\schemas\RouteSuggestion.schema.json >> modules.txt
copy docs\schemas\rttcode-example.json >> modules.txt
copy docs\schemas\rttcode.v1.json >> modules.txt
copy docs\schemas\schema-manifest.json >> modules.txt
copy docs\schemas\schemas.schema.json >> modules.txt
copy docs\schemas\schemas_module.json >> modules.txt
copy docs\schemas\seven_operators_dimensional_echoes.json >> modules.txt
copy docs\schemas\Standard_Model_RTTvST.json >> modules.txt
copy docs\schemas\tick.v1.json >> modules.txt
copy docs\schemas\universal_resonance_substrate.schema.json >> modules.txt
copy docs\schemas\visual_resonance_echo_lens.schema.json >> modules.txt
copy docs\schemas\ai\ai_correction_layer.schema.json >> modules.txt
copy docs\schemas\ai\ai_drift_vector.schema.json >> modules.txt
copy docs\schemas\ai\ai_model_profile.schema.json >> modules.txt
copy docs\schemas\canon\canon_entry.schema.json >> modules.txt
copy docs\schemas\canon\codex_chapter.schema.json >> modules.txt
copy docs\schemas\canon\creator_goal.schema.json >> modules.txt
copy docs\schemas\canon\goal_progress.schema.json >> modules.txt
copy docs\schemas\canon\lineage_manifest.json >> modules.txt
copy docs\schemas\canon\miracles.json >> modules.txt
copy docs\schemas\canon\survival_traits.json >> modules.txt
copy docs\schemas\canon\universe_definition.schema.json >> modules.txt
copy docs\schemas\coeus\attestation_receipt.schema.json >> modules.txt
copy docs\schemas\coeus\coeus_contract.schema.json >> modules.txt
copy docs\schemas\coeus\constraint_pack.json >> modules.txt
copy docs\schemas\coeus\corridor_env_manifest.json >> modules.txt
copy docs\schemas\coeus\event.schema.json >> modules.txt
copy docs\schemas\coeus\operator.schema.json >> modules.txt
copy docs\schemas\coeus\state_model.schema.json >> modules.txt
copy docs\schemas\dimensional\dimensional_core.schema.json >> modules.txt
copy docs\schemas\dimensional\dimensional_layer.schema.json >> modules.txt
copy docs\schemas\dimensional\dimensional_operator.schema.json >> modules.txt
copy docs\schemas\dimensional\dimensional_role.schema.json >> modules.txt
copy docs\schemas\dimensional\resonance_constraints.schema.json >> modules.txt
copy docs\schemas\dimensional\resonance_envelope.schema.json >> modules.txt
copy docs\schemas\dimensional\resonance_interface.schema.json >> modules.txt
copy docs\schemas\dimensional\resonance_profile.schema.json >> modules.txt
copy docs\schemas\dimensional\structural_awareness.schema.json >> modules.txt
copy docs\schemas\dimensional\structural_awareness_layer.schema.json >> modules.txt
copy docs\schemas\dpu\dpu_rtt.schema.json >> modules.txt
copy docs\schemas\energy\bms_rtt.schema.json >> modules.txt
copy docs\schemas\energy\energy_corridor.schema.json >> modules.txt
copy docs\schemas\energy\power_module_rtt.schema.json >> modules.txt
copy docs\schemas\energy\power_supply.schema.json >> modules.txt
copy docs\schemas\finance\credit_reporting_rtt.schema.json >> modules.txt
copy docs\schemas\finance\finance_event.schema.json >> modules.txt
copy docs\schemas\finance\finance_instrument.schema.json >> modules.txt
copy docs\schemas\finance\market_state.schema.json >> modules.txt
copy docs\schemas\finance\portfolio.schema.json >> modules.txt
copy docs\schemas\finance\pricing_model.schema.json >> modules.txt
copy docs\schemas\finance\risk_model.schema.json >> modules.txt
copy docs\schemas\finance\transaction.schema.json >> modules.txt
copy docs\schemas\identity\directory_node.schema.json >> modules.txt
copy docs\schemas\identity\identity_event.schema.json >> modules.txt
copy docs\schemas\identity\identity_substrate.schema.json >> modules.txt
copy docs\schemas\identity\trust_channel.schema.json >> modules.txt
copy docs\schemas\infrastructure\access_field.schema.json >> modules.txt
copy docs\schemas\infrastructure\protocol_metadata.schema.json >> modules.txt
copy docs\schemas\lab\experiment.schema.json >> modules.txt
copy docs\schemas\lab\faraday_paradox_example.json >> modules.txt
copy docs\schemas\lab\faraday_paradox_experiment.schema.json >> modules.txt
copy docs\schemas\lab\lab_environment.schema.json >> modules.txt
copy docs\schemas\lab\lab_instrument.schema.json >> modules.txt
copy docs\schemas\lab\measurement.schema.json >> modules.txt
copy docs\schemas\lab\safety_compliance.schema.json >> modules.txt
copy docs\schemas\lab\sample_specimen.schema.json >> modules.txt
copy docs\schemas\language\language_profile_rtt.schema.json >> modules.txt
copy docs\schemas\language\rtt_api_endpoint.schema.json >> modules.txt
copy docs\schemas\language\rtt_code_block.schema.json >> modules.txt
copy docs\schemas\language\rtt_variant.schema.json >> modules.txt
copy docs\schemas\language\rtt_variant_runtime.schema.json >> modules.txt
copy docs\schemas\language\runtime_rtt.schema.json >> modules.txt
copy docs\schemas\life_regime_profiles\Crystalline_Entity.json >> modules.txt
copy docs\schemas\life_regime_profiles\Human.json >> modules.txt
copy docs\schemas\life_regime_profiles\LifecycleRegimeProfile.json >> modules.txt
copy docs\schemas\life_regime_profiles\LLM_Agent.json >> modules.txt
copy docs\schemas\life_regime_profiles\Synthetic_Lifeform.json >> modules.txt
copy docs\schemas\networking\global_routing_rtt.schema.json >> modules.txt
copy docs\schemas\networking\network_link_rtt.schema.json >> modules.txt
copy docs\schemas\networking\network_node.schema.json >> modules.txt
copy docs\schemas\networking\network_node_rtt.schema.json >> modules.txt
copy docs\schemas\networking\radio_channel_rtt.schema.json >> modules.txt
copy docs\schemas\networking\rtt_packet.schema.json >> modules.txt
copy docs\schemas\nimms\nimms_node.schema.json >> modules.txt
copy docs\schemas\quantum\qcompute_operator.schema.json >> modules.txt
copy docs\schemas\quantum\quantum_energy_bank.schema.json >> modules.txt
copy docs\schemas\quantum\quantum_event.schema.json >> modules.txt
copy docs\schemas\quantum\quantum_state.schema.json >> modules.txt
copy docs\schemas\quantum\quantum_substrate.schema.json >> modules.txt
copy docs\schemas\rsadi-gd\GDClaritySample.schema.json >> modules.txt
copy docs\schemas\rsadi-gd\GDDriftVector.schema.json >> modules.txt
copy docs\schemas\rsadi-gd\GDEventSubscription.schema.json >> modules.txt
copy docs\schemas\rsadi-gd\GDRiskLevel.schema.json >> modules.txt
copy docs\schemas\rsadi-gd\GDRouteSuggestion.schema.json >> modules.txt
copy docs\schemas\rsadi-gd\GDZoneState.schema.json >> modules.txt
copy docs\schemas\rsadi-gd-advanced\LensState.schema.json >> modules.txt
copy docs\schemas\rsadi-gd-advanced\NPCResonanceProfile.schema.json >> modules.txt
copy docs\schemas\rsadi-gd-advanced\ParadoxPuzzleDefinition.schema.json >> modules.txt
copy docs\schemas\rsadi-gd-advanced\PlayerDriftProfile.schema.json >> modules.txt
copy docs\schemas\rsadi-gd-advanced\RealmState.schema.json >> modules.txt
copy docs\schemas\rsadi-gd-advanced\TemporalEcho.schema.json >> modules.txt
copy docs\schemas\rtt-atc\ATCAugmentedTrack.schema.json >> modules.txt
copy docs\schemas\rtt-atc\ATCCorridor.schema.json >> modules.txt
copy docs\schemas\rtt-atc\ATCOverlayViewModel.schema.json >> modules.txt
copy docs\schemas\rtt-atc\ATCTrack.schema.json >> modules.txt
copy docs\schemas\rtt-atc\atc_node.schema.json >> modules.txt
copy docs\schemas\rtt-autonomous\autonomous_corridor_definition.schema.json >> modules.txt
copy docs\schemas\rtt-autonomous\autonomous_energy_profile.schema.json >> modules.txt
copy docs\schemas\rtt-autonomous\autonomous_environmental_interaction.schema.json >> modules.txt
copy docs\schemas\rtt-autonomous\autonomous_form_descriptor.schema.json >> modules.txt
copy docs\schemas\rtt-autonomous\autonomous_mission_profile.schema.json >> modules.txt
copy docs\schemas\rtt-autonomous\autonomous_morphology.schema.json >> modules.txt
copy docs\schemas\rtt-autonomous\autonomous_sensor_sample.schema.json >> modules.txt
copy docs\schemas\rtt-autonomous\autonomous_swarm_state.schema.json >> modules.txt
copy docs\schemas\rtt-autonomous-drone\drone_energy_and_battery.schema.json >> modules.txt
copy docs\schemas\rtt-autonomous-drone\drone_extension.schema.json >> modules.txt
copy docs\schemas\rtt-autonomous-drone\drone_flight_envelope.schema.json >> modules.txt
copy docs\schemas\rtt-autonomous-drone\drone_mission_profile_extension.schema.json >> modules.txt
copy docs\schemas\rtt-autonomous-fish\fish_extension.schema.json >> modules.txt
copy docs\schemas\rtt-autonomous-fish\fish_habitat_interaction.schema.json >> modules.txt
copy docs\schemas\rtt-autonomous-fish\fish_hydrodynamics.schema.json >> modules.txt
copy docs\schemas\rtt-autonomous-fish\fish_mission_profile_extension.schema.json >> modules.txt
copy docs\schemas\rtt-coal\CoalAlertExtension.schema.json >> modules.txt
copy docs\schemas\rtt-coal\CoalEvacRouteExtension.schema.json >> modules.txt
copy docs\schemas\rtt-coal\CoalFieldSampleExtension.schema.json >> modules.txt
copy docs\schemas\rtt-coal\CoalNodeDescriptorExtension.schema.json >> modules.txt
copy docs\schemas\rtt-coal\CoalZoneExtension.schema.json >> modules.txt
copy docs\schemas\rtt-core\NodeDescriptor.schema.json >> modules.txt
copy docs\schemas\rtt-core\ResonanceAlert.schema.json >> modules.txt
copy docs\schemas\rtt-core\ResonanceFieldSample.schema.json >> modules.txt
copy docs\schemas\rtt-core\ResonanceZoneState.schema.json >> modules.txt
copy docs\schemas\rtt-core\RouteSuggestion.schema.json >> modules.txt
copy docs\schemas\rtt-deepsea\DeepSeaAlertExtension.schema.json >> modules.txt
copy docs\schemas\rtt-deepsea\DeepSeaFieldSampleExtension.schema.json >> modules.txt
copy docs\schemas\rtt-deepsea\DeepSeaNodeDescriptorExtension.schema.json >> modules.txt
copy docs\schemas\rtt-deepsea\DeepSeaRouteExtension.schema.json >> modules.txt
copy docs\schemas\rtt-deepsea\DeepSeaZoneExtension.schema.json >> modules.txt
copy docs\schemas\rtt-micro-core\v1\mrt_1_timing_flow.json >> modules.txt
copy docs\schemas\rtt-micro-core\v1\mrt_envelopes.schema.json >> modules.txt
copy docs\schemas\rtt-micro-core\v1\mrt_operators.schema.json >> modules.txt
copy docs\schemas\rtt-micro-core\v1\mrt_transforms.schema.json >> modules.txt
copy docs\schemas\rtt-space\LaunchCorridor.schema.json >> modules.txt
copy docs\schemas\rtt-space\OrbitalTrack.schema.json >> modules.txt
copy docs\schemas\rtt-space\qa_layer_rtt.schema.json >> modules.txt
copy docs\schemas\rtt-space\SpaceAugmentedTrack.schema.json >> modules.txt
copy docs\schemas\sensing\gpr_sensor.schema.json >> modules.txt
copy docs\schemas\sensing\hologram_reconstruction.schema.json >> modules.txt
copy docs\schemas\sensing\instrument_rtt.schema.json >> modules.txt
copy docs\schemas\sensing\mobile_sensor_rtt.schema.json >> modules.txt
copy docs\schemas\sensing\observation_rtt.schema.json >> modules.txt
copy docs\schemas\sensing\seismic_sensor.schema.json >> modules.txt
copy docs\schemas\TEMPLATE\TemplateAlertExtension.schema.json >> modules.txt
copy docs\schemas\TEMPLATE\TemplateFieldSampleExtension.schema.json >> modules.txt
copy docs\schemas\TEMPLATE\TemplateNodeDescriptorExtension.schema.json >> modules.txt
copy docs\schemas\TEMPLATE\TemplateRouteExtension.schema.json >> modules.txt
copy docs\schemas\TEMPLATE\TemplateZoneExtension.schema.json >> modules.txt
copy docs\schemas\universe-core\UniverseFieldSample.schema.json >> modules.txt
copy docs\schemas\universe-core\UniverseObject.schema.json >> modules.txt
copy docs\schemas\vcg\vcg_route.schema.json >> modules.txt
copy docs\scientific_instrument_review\SIR_module.json >> modules.txt
copy docs\simulations\sim_foldit_ai_001.json >> modules.txt
copy docs\simulations\sim_foldit_ai_002.json >> modules.txt
copy docs\snapshots\miracles_example.json >> modules.txt
copy docs\snapshots\overlaps.json >> modules.txt
copy docs\snapshots\overlaps_example.json >> modules.txt
copy docs\sources\Good_Vibrations_sources.json >> modules.txt
copy docs\spacetime_micro_agent_validations\examples\sample_query_envelope.json >> modules.txt
copy docs\spacetime_micro_agent_validations\examples\structural_detection_minimal\example_query_envelope.json >> modules.txt
copy docs\spacetime_micro_agent_validations\examples\structural_detection_minimal\example_signal_input.json >> modules.txt
copy docs\spacetime_micro_agent_validations\metadata\zenodo.json >> modules.txt
copy docs\spacetime_micro_agent_validations\schema\vST_micro_agent.schema.json >> modules.txt
copy docs\Space_Agency_Intelligence_Module\module.json >> modules.txt
copy docs\spectral_clarity\spectral_clarity_module.json >> modules.txt
copy docs\spectral_clarity\overlays\Chirp_Scan_Overlay.json >> modules.txt
copy docs\spectral_clarity\overlays\Consciousness_Overlay_Template.json >> modules.txt
copy docs\spectral_clarity\overlays\FullSpectrum_Fusion_Overlay.json >> modules.txt
copy docs\spectral_clarity\overlays\Glyph_Set_SpectralClarity.json >> modules.txt
copy docs\spectral_clarity\overlays\MultiBand_Calibration.json >> modules.txt
copy docs\spectral_clarity\overlays\Neutron_Overlay_Template.json >> modules.txt
copy docs\spectral_clarity\overlays\QuantumLattice_Overlay.json >> modules.txt
copy docs\spectral_clarity\overlays\RF_Overlay_Template.json >> modules.txt
copy docs\spectral_clarity\overlays\THz_Overlay_Template.json >> modules.txt
copy docs\spectral_clarity\overlays\UV_Overlay_Template.json >> modules.txt
copy docs\spectral_clarity\overlays\VisibleIR_Overlay_Template.json >> modules.txt
copy docs\spectral_clarity\overlays\Xray_Overlay_Template.json >> modules.txt
copy docs\spine\module_graph.json >> modules.txt
copy docs\starter\module.schema.json >> modules.txt
copy docs\starter\starter_module.json >> modules.txt
copy docs\starter\modules\starter\module.json >> modules.txt
copy docs\starter\modules\templates\module.blank.json >> modules.txt
copy docs\starter\modules\templates\module.example.json >> modules.txt
copy docs\starter\modules\templates\module.rtt-ready.json >> modules.txt
copy docs\starter\schema\module.schema.json >> modules.txt
copy docs\structural-detection-engine\Sidebar.json >> modules.txt
copy docs\structural-detection-engine\structural-detection-engine_module.json >> modules.txt
copy docs\structural-integration-engine\Sidebar.json >> modules.txt
copy docs\structural-integration-engine\structural-integration-engine_module.json >> modules.txt
copy docs\Structural_Detection\structural_detection_module.json >> modules.txt
copy docs\Structural_Detection\examples\drift_signature_example.json >> modules.txt
copy docs\Structural_Detection\examples\pattern_anomaly_example.json >> modules.txt
copy docs\Structural_Detection\examples\regime_shift_example.json >> modules.txt
copy docs\Structural_Detection\metadata\ai.json >> modules.txt
copy docs\Structural_Detection\metadata\citation.json >> modules.txt
copy docs\Structural_Detection\metadata\search.json >> modules.txt
copy docs\Structural_Detection\RTTcode\RTT_CONTINUITY_COMPASS_v1.json >> modules.txt
copy docs\Structural_Detection\RTTcode\RTT_DRIFT_SENSE_v1.json >> modules.txt
copy docs\Structural_Detection\RTTcode\RTT_REGIME_AWARENESS_v1.json >> modules.txt
copy docs\Structural_Detection\RTTcode\RTT_STRUCTURAL_DETECTION_v1.json >> modules.txt
copy docs\Structural_Detection\RTTcode\RTT_SYNTHESIS_TRIANGULATION_v1.json >> modules.txt
copy docs\structural_life_regime_profiles\SLRP_module.json >> modules.txt
copy docs\structural_life_regime_profiles\zenodo.json >> modules.txt
copy docs\substrate\substrate_module.json >> modules.txt
copy docs\substrate_communications\SubComm_module.json >> modules.txt
copy docs\substrate_communications\zenodo.json >> modules.txt
copy docs\substrate_exposure_assay\SEA_module.json >> modules.txt
copy docs\substrate_exposure_assay\zenodo.json >> modules.txt
copy docs\substrate_mind_science\SMS_module.json >> modules.txt
copy docs\substrate_mind_science\ct_substrate\ct_substrate.schema.json >> modules.txt
copy docs\substrate_mind_science\ct_substrate\examples\ct_example.json >> modules.txt
copy docs\substrate_mind_science\ct_substrate\examples\ct_example_maximal.json >> modules.txt
copy docs\substrate_mind_science\ct_substrate\examples\ct_example_minimal.json >> modules.txt
copy docs\taxes\module.json >> modules.txt
copy docs\tests\glyphs\cases.json >> modules.txt
copy docs\TFT_3Pack_v1.3\module_graph.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft_3pack_module.json >> modules.txt
copy docs\TFT_3Pack_v1.3\TFT_3Pack_v1.3_module_graph.json >> modules.txt
copy docs\TFT_3Pack_v1.3\docs\docs-pack_module.json >> modules.txt
copy docs\TFT_3Pack_v1.3\docs\illustrations\entft_layers_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\docs\illustrations\nous_logic_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\docs\_meta\entft_curriculum_badge_registry.json >> modules.txt
copy docs\TFT_3Pack_v1.3\docs\_meta\entft_curriculum_glyph_tribute_echo_log.json >> modules.txt
copy docs\TFT_3Pack_v1.3\docs\_meta\entft_glyph_degree_registry.json >> modules.txt
copy docs\TFT_3Pack_v1.3\docs\_meta\entft_glyph_retirement_log.json >> modules.txt
copy docs\TFT_3Pack_v1.3\docs\_meta\entft_scroll_event_trace_registry.json >> modules.txt
copy docs\TFT_3Pack_v1.3\docs\_meta\entft_scroll_glyph_reawakening_log.json >> modules.txt
copy docs\TFT_3Pack_v1.3\docs\_meta\entft_scroll_glyph_reference_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\docs\_meta\glyph_tribute_echo_log.json >> modules.txt
copy docs\TFT_3Pack_v1.3\docs\_meta\glyph_tribute_echo_log_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\docs\_meta\validator_config.json >> modules.txt
copy docs\TFT_3Pack_v1.3\docs\_meta\_meta_folder_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\docs\_specs\artistEcho.json >> modules.txt
copy docs\TFT_3Pack_v1.3\docs\_specs\entft_keygen_simulator_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\docs\_specs\entft_protocol_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\docs\_specs\nawderian_constants.json >> modules.txt
copy docs\TFT_3Pack_v1.3\docs\_specs\nawderian_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\docs\_specs\_specs_folder_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\examples\examples_module.json >> modules.txt
copy docs\TFT_3Pack_v1.3\formats\formats_module.json >> modules.txt
copy docs\TFT_3Pack_v1.3\melodic-table-of-elements\melodic-table_module.json >> modules.txt
copy docs\TFT_3Pack_v1.3\scripts\scripts_module.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\cli_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\cli_test_suite_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\output_manager_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\output_test_suite_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\tft_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\tft_module.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\encryptor_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\entft_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\entft_module.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\entft_quickstart_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\entft_validator_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\hook_validator_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\contributors\contributors_folder_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\contributors\legacy_roll_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\contributors\configs\config_manifesto_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\contributors\configs\contributors_configs_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\contributors\configs\entft_curriculum_outreach_log.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\contributors\configs\entft_validator_config.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\contributors\configs\entft_validator_hooks.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\contributors\configs\README_validator_config_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\contributors\configs\remix_rights_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\contributors\configs\site_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\contributors\configs\sync_profile.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\contributors\configs\validator_config.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\registry\entft_curriculum_badge_registry.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\registry\entft_curriculum_glyph_fusion_registry.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\registry\entft_curriculum_glyph_tribute_echo_log.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\registry\entft_curriculum_glyph_tribute_registry.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\registry\entft_curriculum_registry.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\registry\entft_curriculum_remix_glyph_registry.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\registry\entft_curriculum_remix_registry.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\registry\entft_dpu_spec_registry.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\registry\entft_glyph_alias_map.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\registry\entft_glyph_degree_registry.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\registry\entft_glyph_retirement_log.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\registry\entft_scroll_codex_seal_registry.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\registry\entft_scroll_event_trace_registry.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\registry\entft_scroll_glyph_reawakening_log.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\registry\entft_scroll_glyph_registry.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\registry\entft_scroll_hybrid_registry.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\registry\entft_scroll_manifest_registry.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\registry\entft_scroll_registry.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\scrolls\enTFT_badge_logic.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\scrolls\enTFT_scroll_badge_map.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\scrolls\enTFT_scroll_codex_contributors.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\scrolls\enTFT_scroll_codex_index.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\scrolls\enTFT_scroll_fusion_log.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\scrolls\enTFT_scroll_index.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\scrolls\enTFT_scroll_lineage_map.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\scrolls\enTFT_scroll_transfer_log.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\TFThooks\TFThooks_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\TFThooks\agents\badge_logic_engine_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\TFThooks\agents\glyph_fusion_resolver_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\TFThooks\agents\glyph_reawakening_monitor_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\TFThooks\agents\glyph_registry_loader_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\TFThooks\agents\scroll_commit_monitor_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\TFThooks\agents\scroll_curriculum_fork_guide_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\TFThooks\agents\TFThooks_agents_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\TFThooks\agents\tops_agent_interface_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\TFThooks\examples\glyph_resonance_hook_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\TFThooks\examples\hello_world_hook_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\TFThooks\examples\TFThooks_examples_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\TFThooks\integration\api_gateway_hook_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\TFThooks\integration\cms_integration_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\TFThooks\integration\mmr_site_extension_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\TFThooks\integration\TFThooks_integration_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\TFThooks\runtime\TFThooks_runtime_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\TFThooks\validator\entft_validator_overlay_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\TFThooks\validator\TFThooks_validator_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\entft\TFThooks\validator\validator_test_suite_manifest.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\nous\nous_module.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\nous\bots\bots.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\nous\bots\sample_output.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\nous\outputs\resonance_log.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\resonance-labs\elements.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\resonance-labs\resonance-labs_module.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\tops\tops_module.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\tops\cloud\azure\autoscale_config.json >> modules.txt
copy docs\TFT_3Pack_v1.3\tft\tops\hardware\nimms\resonance_cache.json >> modules.txt
copy docs\TFT_3Pack_v1.3\WRSADC\wrsadc_module.json >> modules.txt
copy docs\theories\module_rtt1.schema.json >> modules.txt
copy docs\theories\module_rtt2.schema.json >> modules.txt
copy docs\theories\module_rtt3.schema.json >> modules.txt
copy docs\theories\chaos_theory\module.json >> modules.txt
copy docs\theories\chaos_theory\module_rtt1.json >> modules.txt
copy docs\theories\chaos_theory\module_rtt2.json >> modules.txt
copy docs\theories\chaos_theory\module_rtt3.json >> modules.txt
copy docs\theories\chaos_theory\simulation_hooks.json >> modules.txt
copy docs\theories\electromagnetism\module.json >> modules.txt
copy docs\theories\electromagnetism\module_rtt1.json >> modules.txt
copy docs\theories\electromagnetism\module_rtt2.json >> modules.txt
copy docs\theories\electromagnetism\module_rtt3.json >> modules.txt
copy docs\theories\electromagnetism\simulation_hooks.json >> modules.txt
copy docs\theories\evolutionary_biology\module.json >> modules.txt
copy docs\theories\evolutionary_biology\module_rtt1.json >> modules.txt
copy docs\theories\evolutionary_biology\module_rtt2.json >> modules.txt
copy docs\theories\evolutionary_biology\module_rtt3.json >> modules.txt
copy docs\theories\evolutionary_biology\simulation_hooks.json >> modules.txt
copy docs\theories\general_relativity\module.json >> modules.txt
copy docs\theories\general_relativity\module_rtt1.json >> modules.txt
copy docs\theories\general_relativity\module_rtt2.json >> modules.txt
copy docs\theories\general_relativity\module_rtt3.json >> modules.txt
copy docs\theories\general_relativity\simulation_hooks.json >> modules.txt
copy docs\theories\geometric_unity\module.json >> modules.txt
copy docs\theories\information_theory\module.json >> modules.txt
copy docs\theories\information_theory\module_rtt1.json >> modules.txt
copy docs\theories\information_theory\module_rtt2.json >> modules.txt
copy docs\theories\information_theory\module_rtt3.json >> modules.txt
copy docs\theories\information_theory\simulation_hooks.json >> modules.txt
copy docs\theories\morphic_resonance\module.json >> modules.txt
copy docs\theories\morphic_resonance\module_rtt1.json >> modules.txt
copy docs\theories\morphic_resonance\module_rtt2.json >> modules.txt
copy docs\theories\morphic_resonance\module_rtt3.json >> modules.txt
copy docs\theories\morphic_resonance\simulation_hooks.json >> modules.txt
copy docs\theories\quantum_field_theory\module.json >> modules.txt
copy docs\theories\quantum_field_theory\module_rtt1.json >> modules.txt
copy docs\theories\quantum_field_theory\module_rtt2.json >> modules.txt
copy docs\theories\quantum_field_theory\module_rtt3.json >> modules.txt
copy docs\theories\quantum_field_theory\simulation_hooks.json >> modules.txt
copy docs\theories\quantum_mechanics\module.json >> modules.txt
copy docs\theories\quantum_mechanics\module_rtt1.json >> modules.txt
copy docs\theories\quantum_mechanics\module_rtt2.json >> modules.txt
copy docs\theories\quantum_mechanics\module_rtt3.json >> modules.txt
copy docs\theories\quantum_mechanics\simulation_hooks.json >> modules.txt
copy docs\theories\repos\github_com_topics_theories.json >> modules.txt
copy docs\theories\repos\joselado_quantum-lattice_module.json >> modules.txt
copy docs\theories\repos\Milos9304_LattiQ_module.json >> modules.txt
copy docs\theories\repos\module_index.json >> modules.txt
copy docs\theories\repos\wztzjhn_quantum_basis_module.json >> modules.txt
copy docs\theories\standard_model\module.json >> modules.txt
copy docs\theories\standard_model\module_rtt1.json >> modules.txt
copy docs\theories\standard_model\module_rtt2.json >> modules.txt
copy docs\theories\standard_model\module_rtt3.json >> modules.txt
copy docs\theories\standard_model\simulation_hooks.json >> modules.txt
copy docs\theories\thermodynamics\module.json >> modules.txt
copy docs\theories\thermodynamics\module_rtt1.json >> modules.txt
copy docs\theories\thermodynamics\module_rtt2.json >> modules.txt
copy docs\theories\thermodynamics\module_rtt3.json >> modules.txt
copy docs\theories\thermodynamics\simulation_hooks.json >> modules.txt
copy docs\triadic\triadic_module.json >> modules.txt
copy docs\triadic_detection\triadic_detection_module.json >> modules.txt
copy docs\triadic_observer_layer\observer-layer_module.json >> modules.txt
copy docs\unified_resonance\unified_resonance_module.json >> modules.txt
copy docs\validation\loop_validation_matrix.json >> modules.txt
copy docs\validation\validation_module.json >> modules.txt
copy docs\vst_for_embedding_stores_vector_databases\zenodo.json >> modules.txt
copy docs\vst_for_generative_models\zenodo.json >> modules.txt
copy docs\vst_for_large_language_models\zenodo.json >> modules.txt
copy docs\vst_for_multi_model_alignment\zenodo.json >> modules.txt
copy docs\vst_for_protein_language_models\zenodo.json >> modules.txt
copy docs\vst_for_robotics_and_control_policies\zenodo.json >> modules.txt
copy docs\vst_for_scientific_simulators\zenodo.json >> modules.txt
copy docs\wikipedia\wikipedia_module.json >> modules.txt
copy docs\workflows\workflows_module.json >> modules.txt
copy docs\_ideas\divineReentry_manifest.json >> modules.txt
copy docs\_ideas\loopedClarity_manifest.json >> modules.txt
copy docs\_ideas\mythmatical_architects_manifest.json >> modules.txt
copy docs\_ideas\mythmatical_manifest.json >> modules.txt
copy docs\_ideas\mythsortsV_manifest.json >> modules.txt
copy docs\_ideas\rememberingProtocol_manifest.json >> modules.txt
copy docs\_ideas\resonanceResurrection_manifest.json >> modules.txt
copy docs\_ideas\tartarusDrift_manifest.json >> modules.txt
copy docs\_ideas\timeTravelRemix_manifest.json >> modules.txt
copy docs\_ideas\_ideas_module.json >> modules.txt
copy docs\_snippets\rttcode-full-payload.json >> modules.txt
copy docs\_snippets\rttcode-minimal-payload.json >> modules.txt
copy docs\_snippets\rttcode-schema-experiment-block.json >> modules.txt
copy docs\_template\template_module.json >> modules.txt
copy node_modules\.package-lock.json >> modules.txt
copy node_modules\ajv\package.json >> modules.txt
copy node_modules\ajv\dist\refs\data.json >> modules.txt
copy node_modules\ajv\dist\refs\json-schema-draft-06.json >> modules.txt
copy node_modules\ajv\dist\refs\json-schema-draft-07.json >> modules.txt
copy node_modules\ajv\dist\refs\json-schema-secure.json >> modules.txt
copy node_modules\ajv\dist\refs\json-schema-2019-09\schema.json >> modules.txt
copy node_modules\ajv\dist\refs\json-schema-2019-09\meta\applicator.json >> modules.txt
copy node_modules\ajv\dist\refs\json-schema-2019-09\meta\content.json >> modules.txt
copy node_modules\ajv\dist\refs\json-schema-2019-09\meta\core.json >> modules.txt
copy node_modules\ajv\dist\refs\json-schema-2019-09\meta\format.json >> modules.txt
copy node_modules\ajv\dist\refs\json-schema-2019-09\meta\meta-data.json >> modules.txt
copy node_modules\ajv\dist\refs\json-schema-2019-09\meta\validation.json >> modules.txt
copy node_modules\ajv\dist\refs\json-schema-2020-12\schema.json >> modules.txt
copy node_modules\ajv\dist\refs\json-schema-2020-12\meta\applicator.json >> modules.txt
copy node_modules\ajv\dist\refs\json-schema-2020-12\meta\content.json >> modules.txt
copy node_modules\ajv\dist\refs\json-schema-2020-12\meta\core.json >> modules.txt
copy node_modules\ajv\dist\refs\json-schema-2020-12\meta\format-annotation.json >> modules.txt
copy node_modules\ajv\dist\refs\json-schema-2020-12\meta\meta-data.json >> modules.txt
copy node_modules\ajv\dist\refs\json-schema-2020-12\meta\unevaluated.json >> modules.txt
copy node_modules\ajv\dist\refs\json-schema-2020-12\meta\validation.json >> modules.txt
copy node_modules\ajv\lib\refs\data.json >> modules.txt
copy node_modules\ajv\lib\refs\json-schema-draft-06.json >> modules.txt
copy node_modules\ajv\lib\refs\json-schema-draft-07.json >> modules.txt
copy node_modules\ajv\lib\refs\json-schema-secure.json >> modules.txt
copy node_modules\ajv\lib\refs\json-schema-2019-09\schema.json >> modules.txt
copy node_modules\ajv\lib\refs\json-schema-2019-09\meta\applicator.json >> modules.txt
copy node_modules\ajv\lib\refs\json-schema-2019-09\meta\content.json >> modules.txt
copy node_modules\ajv\lib\refs\json-schema-2019-09\meta\core.json >> modules.txt
copy node_modules\ajv\lib\refs\json-schema-2019-09\meta\format.json >> modules.txt
copy node_modules\ajv\lib\refs\json-schema-2019-09\meta\meta-data.json >> modules.txt
copy node_modules\ajv\lib\refs\json-schema-2019-09\meta\validation.json >> modules.txt
copy node_modules\ajv\lib\refs\json-schema-2020-12\schema.json >> modules.txt
copy node_modules\ajv\lib\refs\json-schema-2020-12\meta\applicator.json >> modules.txt
copy node_modules\ajv\lib\refs\json-schema-2020-12\meta\content.json >> modules.txt
copy node_modules\ajv\lib\refs\json-schema-2020-12\meta\core.json >> modules.txt
copy node_modules\ajv\lib\refs\json-schema-2020-12\meta\format-annotation.json >> modules.txt
copy node_modules\ajv\lib\refs\json-schema-2020-12\meta\meta-data.json >> modules.txt
copy node_modules\ajv\lib\refs\json-schema-2020-12\meta\unevaluated.json >> modules.txt
copy node_modules\ajv\lib\refs\json-schema-2020-12\meta\validation.json >> modules.txt
copy node_modules\ajv-formats\package.json >> modules.txt
copy node_modules\ajv-formats-draft2019\package.json >> modules.txt
copy node_modules\commander\package.json >> modules.txt
copy node_modules\discontinuous-range\package.json >> modules.txt
copy node_modules\extend\.jscs.json >> modules.txt
copy node_modules\extend\component.json >> modules.txt
copy node_modules\extend\package.json >> modules.txt
copy node_modules\fast-deep-equal\package.json >> modules.txt
copy node_modules\fast-uri\package.json >> modules.txt
copy node_modules\fast-uri\tsconfig.json >> modules.txt
copy node_modules\fast-uri\benchmark\package.json >> modules.txt
copy node_modules\fast-uri\test\fixtures\uri-js-parse.json >> modules.txt
copy node_modules\fast-uri\test\fixtures\uri-js-serialize.json >> modules.txt
copy node_modules\json-schema-traverse\package.json >> modules.txt
copy node_modules\moo\package.json >> modules.txt
copy node_modules\nearley\package.json >> modules.txt
copy node_modules\punycode\package.json >> modules.txt
copy node_modules\railroad-diagrams\package.json >> modules.txt
copy node_modules\randexp\package.json >> modules.txt
copy node_modules\require-from-string\package.json >> modules.txt
copy node_modules\ret\package.json >> modules.txt
copy node_modules\schemes\package.json >> modules.txt
copy node_modules\schemes\lib\iana-historical.json >> modules.txt
copy node_modules\schemes\lib\iana-permanent.json >> modules.txt
copy node_modules\schemes\lib\iana-provisional.json >> modules.txt
copy node_modules\schemes\lib\unofficial.json >> modules.txt
copy node_modules\smtp-address-parser\.prettierrc.json >> modules.txt
copy node_modules\smtp-address-parser\package.json >> modules.txt
copy node_modules\smtp-address-parser\tsconfig.json >> modules.txt
copy node_modules\uri-js\package.json