@echo off
echo Creating...
echo . > a_Badge.html
echo . > a_Capture.md
echo . > a_Diff_Table.md
echo . > a_Hero_Image.png
echo . > a_Sidebar_Audit.html
echo . > index.md
echo . > module.json
echo . > README.md
echo . > diagnostic/dimensional_envelope.min.md
echo . > diagnostic/dimensional_trace.min.json
echo . > diagnostic/dimensional_map.min.json
echo . > diagnostic/dimensional_diagnostic_trace.md
echo . > diagnostic/drift_trace.min.json  
echo . > diagnostic/drift_map.min.json  
echo . > diagnostic/drift_envelope.min.md  
echo . > diagnostic/drift_diagnostic_trace.md
echo . > diagnostic/paradox_trace.min.json  
echo . > diagnostic/paradox_map.min.json  
echo . > diagnostic/paradox_envelope.min.md  
echo . > diagnostic/paradox_diagnostic_trace.md
echo . > diagnostic/resonance_trace.min.json  
echo . > diagnostic/resonance_map.min.json  
echo . > diagnostic/resonance_envelope.min.md  
echo . > diagnostic/resonance_diagnostic_trace.md
echo . > diagnostic/nudge_diagnostic.json  
echo . > diagnostic/nudge_diagnostic.schema.json  
echo . > diagnostic/nudge_diagnostic.min.json  
echo . > diagnostic/nudge_diagnostic.min.schema.json  
echo . > diagnostic/nudge_diagnostic.example.json  
echo . > diagnostic/nudge_diagnostic.md  
echo . > diagnostic/nudge_trace.json  
echo . > diagnostic/nudge_trace.schema.json  
echo . > diagnostic/nudge_trace.md  
echo . > diagnostic/nudge_map.json  
echo . > diagnostic/nudge_map.schema.json  
echo . > diagnostic/nudge_map.md  
echo . > diagnostic/nudge_envelope.json  
echo . > diagnostic/nudge_envelope.schema.json  
echo . > diagnostic/nudge_envelope.min.json  
echo . > diagnostic/nudge_envelope.md  
echo . > diagnostic/teleconnection_diagnostic.json  
echo . > diagnostic/teleconnection_diagnostic.schema.json  
echo . > diagnostic/teleconnection_diagnostic.min.json  
echo . > diagnostic/teleconnection_diagnostic.min.schema.json  
echo . > diagnostic/teleconnection_diagnostic.example.json  
echo . > diagnostic/teleconnection_diagnostic.md  
echo . > diagnostic/teleconnection_trace.json  
echo . > diagnostic/teleconnection_trace.schema.json  
echo . > diagnostic/teleconnection_trace.md  
echo . > diagnostic/teleconnection_map.json  
echo . > diagnostic/teleconnection_map.schema.json  
echo . > diagnostic/teleconnection_map.md  
echo . > diagnostic/teleconnection_envelope.json  
echo . > diagnostic/teleconnection_envelope.schema.json  
echo . > diagnostic/teleconnection_envelope.min.json  
echo . > diagnostic/teleconnection_envelope.md  
echo . > diagnostic/forcing_diagnostic.json  
echo . > diagnostic/forcing_diagnostic.schema.json  
echo . > diagnostic/forcing_diagnostic.min.json  
echo . > diagnostic/forcing_diagnostic.min.schema.json  
echo . > diagnostic/forcing_diagnostic.example.json  
echo . > diagnostic/forcing_diagnostic.md  
echo . > diagnostic/forcing_trace.json  
echo . > diagnostic/forcing_trace.schema.json  
echo . > diagnostic/forcing_trace.md  
echo . > diagnostic/forcing_map.json  
echo . > diagnostic/forcing_map.schema.json  
echo . > diagnostic/forcing_map.md  
echo . > diagnostic/forcing_envelope.json  
echo . > diagnostic/forcing_envelope.schema.json  
echo . > diagnostic/forcing_envelope.min.json  
echo . > diagnostic/forcing_envelope.md  
echo . > diagnostic/composition_diagnostic.json  
echo . > diagnostic/composition_diagnostic.schema.json  
echo . > diagnostic/composition_diagnostic.min.json  
echo . > diagnostic/composition_diagnostic.min.schema.json  
echo . > diagnostic/composition_diagnostic.example.json  
echo . > diagnostic/composition_diagnostic.md  
echo . > diagnostic/composition_trace.json  
echo . > diagnostic/composition_trace.schema.json  
echo . > diagnostic/composition_trace.md  
echo . > diagnostic/composition_map.json  
echo . > diagnostic/composition_map.schema.json  
echo . > diagnostic/composition_map.md  
echo . > diagnostic/composition_envelope.json  
echo . > diagnostic/composition_envelope.schema.json  
echo . > diagnostic/composition_envelope.min.json  
echo . > diagnostic/composition_envelope.md  
echo . > diagnostic/hydrospheric_envelope.*  
echo . > diagnostic/hydrospheric_diagnostic.json  
echo . > diagnostic/hydrospheric_diagnostic.schema.json  
echo . > diagnostic/hydrospheric_diagnostic.min.json  
echo . > diagnostic/hydrospheric_diagnostic.min.schema.json  
echo . > diagnostic/hydrospheric_diagnostic.example.json  
echo . > diagnostic/hydrospheric_diagnostic.md  
echo . > diagnostic/hydrospheric_trace.json  
echo . > diagnostic/hydrospheric_trace.schema.json  
echo . > diagnostic/hydrospheric_trace.md  
echo . > diagnostic/hydrospheric_map.json  
echo . > diagnostic/hydrospheric_map.schema.json  
echo . > diagnostic/hydrospheric_map.md  
echo . > diagnostic/hydrospheric_envelope.json  
echo . > diagnostic/hydrospheric_envelope.schema.json  
echo . > diagnostic/hydrospheric_envelope.min.json  
echo . > diagnostic/hydrospheric_envelope.md  
echo . > diagnostic/thermodynamics_diagnostic.json  
echo . > diagnostic/thermodynamics_diagnostic.schema.json  
echo . > diagnostic/thermodynamics_diagnostic.min.json  
echo . > diagnostic/thermodynamics_diagnostic.min.schema.json  
echo . > diagnostic/thermodynamics_diagnostic.example.json  
echo . > diagnostic/thermodynamics_diagnostic.md  
echo . > diagnostic/thermodynamics_trace.json  
echo . > diagnostic/thermodynamics_trace.schema.json  
echo . > diagnostic/thermodynamics_trace.md  
echo . > diagnostic/thermodynamics_map.json  
echo . > diagnostic/thermodynamics_map.schema.json  
echo . > diagnostic/thermodynamics_map.md  
echo . > diagnostic/thermodynamics_envelope.json  
echo . > diagnostic/thermodynamics_envelope.schema.json  
echo . > diagnostic/thermodynamics_envelope.min.json  
echo . > diagnostic/thermodynamics_envelope.md  
echo . > diagnostic/dynamics_diagnostic.json  
echo . > diagnostic/dynamics_diagnostic.schema.json  
echo . > diagnostic/dynamics_diagnostic.min.json  
echo . > diagnostic/dynamics_diagnostic.min.schema.json  
echo . > diagnostic/dynamics_diagnostic.example.json  
echo . > diagnostic/dynamics_diagnostic.md  
echo . > diagnostic/dynamics_trace.json  
echo . > diagnostic/dynamics_trace.schema.json  
echo . > diagnostic/dynamics_trace.md  
echo . > diagnostic/dynamics_map.json  
echo . > diagnostic/dynamics_map.schema.json  
echo . > diagnostic/dynamics_map.md  
echo . > diagnostic/dynamics_envelope.json  
echo . > diagnostic/dynamics_envelope.schema.json  
echo . > diagnostic/dynamics_envelope.min.json  
echo . > diagnostic/dynamics_envelope.md  
echo . > session/session_index.md  
echo . > session/session_trace.md  
echo . > session/session_context.md  
echo . > registry/index.md  
echo . > registry/module_registry.json  
echo . > registry/module_registry.md
echo . > maps/clarity_map.md  
echo . > maps/teleconnection_map.md  
echo . > maps/forcing_map.md  
echo . > maps/composition_map.md  
echo . > maps/hydrospheric_map.md  
echo . > maps/thermodynamics_map.md  
echo . > maps/dynamics_map.md
