@echo off
echo Creating ...

md docs
md ai
md ai-drift-calibration
md AI_Resonance_Seed
md alphafold_substrate_alignments
md apirtt
md archive_org
md arrival_substrate_model
md assets
md atomic_clocks
md audio_industry_reviewed
md badges
md boson-substrate-model
md bridges
md charts
md clients
md code
md Coeus
md Conditions_Substrate_Model
md configs
md consciousness_substrate_model
md contributors
md corpus
md curriculum
md data
md datacenter_reports
md dimensional_substrate_regime_scanning_protocol
md dimensional_substrate_structures
md ecoechosystem
md education
md alignment
md animals
md astrology
md awareness
md BRA
md CivRegimeStack
md ebooks
md Grammar_for_Intelligence
md equations
md peira
md polisci
md QnA_Atlas
md subjects
md education-Toolbox
md translations
md energy
md enterprise_structural_awareness
md Expectations
md facilities
md feedback
md creation_guide
md ipd_12
md Framework_Field_Theory
md Framework_Field_Theory-Analyzer
md gallery
md global_energy_regime_awareness
md glyphic_resonance
md Governance_Substrate_Model
md Governance_Substrate_Model-Analyzer
md Human_Resources
md Incident_Substrate_Model
md Integrations
md Integrations-UE6
md Inverted_Economics
md inverted_star_ontology
md lactos
md Law
md Low_Dimensional_Structures
md manufacturing_substrate_regime_model
md medicine
md metadata
md Mode
md nist
md NoS
md Opacity
md operators
md operators-teaching_bundle
md pantheons
md andean
md celtic
md chinese
md egyptian
md greek
md hindu
md japanese
md kemetic
md mesoamerican
md norse
md north_american_woodland
md sumerian
md yoruba
md Paradoxes_canon
md Philanthropy
md projects
md nasa_hposs_tminus10.md
md prompts
md rtt_infinity
md regime_blindness_checklist
md registry
md religious_substrate_grammar_model
md Research
md Research-agentic
md Research-Toolbox
md Resilience_Checker
md resonance-substrate-model
md resonance_atlas
md rtt
md rtt-1
md rtt-12
md rtt-2
md rtt-3
md rtt-app
md rtt-c64host
md rtt-codes
md rtt-codex
md rtt-Coherence_Tensor_Engine
md rtt-Cross_Domain_Causality_Weaver
md rtt-D369_Chip_Spec
md rtt-Dimensional_Resonance_Scanner
md rtt-Drift_Sentinel
md rtt-Echo_Classifier
md rtt-emotions
md rtt-extension
md rtt-Harmonic_Stability_Profile
md rtt-Inside
md rtt-InsideBenchmarks
md rtt-InsideCiscomanifest
md rtt-InsideEnterprise
md rtt-InsideInternet2
md rtt-InsidePython
md rtt-InsideqCompute
md rtt-micro_core
md rtt-Morphic_Resonance
md rtt-Paradox_Gradient_Analyzer
md rtt-Regime_Interlock_Mapper
md rtt-sdk
md rtt-Stability_Basin_Cartographer
md rtt-store
md rtt-Structural_Faultline_Detector
md rtt-Substrate_Flow
md rtt-Temporal_Regime_Sequencer
md rtt-The_Inverted_Star
md rtt-Triadic_Echo_Lattice
md rtt-Triadic_Regime_Synthesizer
md SARG
md schemas
md scientific_instrument_review
md spectral_clarity
md starter
md structural-detection-engine
md structural-integration-engine
md Structural_Detection
md structural_life_regime_profiles
md substrate
md substrate_communications
md substrate_exposure_assay
md substrate_mind_science
md taxes
md TFT_3Pack_v1.3
md tft-entft
md tft-nous
md tft-resonance-labs
md tft-tops
md WRSADC
md theories
md chaos_theory
md electromagnetism
md evolutionary_biology
md general_relativity
md geometric_unity
md information_theory
md morphic_resonance
md quantum_field_theory
md quantum_mechanics
md standard_model
md thermodynamics
md triadic
md triadic_detection
md triadic_observer_layer
md unified_resonance
md validation
md wikipedia
md _ideas
md _template