title: "RTT Starter Kit"
description: "Student and Instructor Documentation"
theme: "just-the-docs"

just_the_docs:
  search_enabled: true
  navigation_depth: 3
  show_toc: true

markdown: kramdown
kramdown:
  input: GFM

collections:
  rtt:
    output: true
    permalink: /rtt/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: default

# Sidebar ordering
nav_order: 1

# Pretty URLs
permalink: pretty
