graph TD

  Core_Concepts --> Gravity_Foundations
  Gravity_Foundations --> Drift_Taxonomy
  Gravity_Foundations --> FFF_Gravity

  RTT_Operators --> Operator_Families

  Drift_Taxonomy --> d_Capture
  Drift_Taxonomy --> d_Classify
  Drift_Taxonomy --> d_Operators
  Drift_Taxonomy --> d_Examples
  Drift_Taxonomy --> d_Paper

  Gravity_Foundations --> Module_Graph

  subgraph Drift_Taxonomy_Files
    d_Capture
    d_Classify
    d_Operators
    d_Examples
    d_Paper
  end
