@echo off
echo Creating 123 ABOUT.md's
copy con ABOUT.md
copy con ai\ABOUT.md
copy con ai-drift-calibration\ABOUT.md
copy con AI_Resonance_Seed\ABOUT.md
copy con alphafold_substrate_alignments\ABOUT.md
copy con api\rtt\ABOUT.md
copy con archive_experiments\engine\ABOUT.md
copy con arrival_substrate_model\ABOUT.md
copy con assets\ABOUT.md
copy con atomic_clocks\ABOUT.md
copy con audio_industry_reviewed\ABOUT.md
copy con badges\ABOUT.md
copy con boson-substrate-model\ABOUT.md
copy con bridges\ABOUT.md
copy con charts\ABOUT.md
copy con clients\ABOUT.md
copy con Coeus\ABOUT.md
copy con configs\ABOUT.md
copy con consciousness_substrate_model\ABOUT.md
copy con contributors\ABOUT.md
copy con corpus\ABOUT.md
copy con curriculum\ABOUT.md
copy con data\ABOUT.md
copy con dimensional_substrate_regime_scanning_protocol\ABOUT.md
copy con dimensional_substrate_structures\ABOUT.md
copy con domain_tool_primers\ABOUT.md
copy con ecoechosystem\ABOUT.md
copy con education\ABOUT.md
copy con education\alignment\ABOUT.md
copy con education\animals\ABOUT.md
copy con education\astrology\ABOUT.md
copy con education\awareness\ABOUT.md
copy con education\BRA\ABOUT.md
copy con education\CivRegimeStack\ABOUT.md
copy con education\ebooks\ABOUT.md
copy con education\equations\ABOUT.md
copy con education\peira\ABOUT.md
copy con education\polisci\ABOUT.md
copy con education\QnA_Atlas\ABOUT.md
copy con education\subjects\ABOUT.md
copy con education\translations\ABOUT.md
copy con energy\ABOUT.md
copy con enterprise_structural_awareness\ABOUT.md
copy con facilities\ABOUT.md
copy con feedback\ABOUT.md
copy con gallery\ABOUT.md
copy con global_energy_regime_awareness\ABOUT.md
copy con glyphic_resonance\ABOUT.md
copy con glyphs\ABOUT.md
copy con governance\ABOUT.md
copy con Governance_Substrate_Model\ABOUT.md
copy con Governance_Substrate_Model\Analyzer\ABOUT.md
copy con honor_roll\ABOUT.md
copy con Inverted_Economics\ABOUT.md
copy con inverted_star_ontology\ABOUT.md
copy con labs\ABOUT.md
copy con lactos\ABOUT.md
copy con legal\ABOUT.md
copy con library\ABOUT.md
copy con Low_Dimensional_Structures\ABOUT.md
copy con manufacturing_substrate_regime_model\ABOUT.md
copy con media_substrate_model\ABOUT.md
copy con media_substrate_model\analyzer\ABOUT.md
copy con metadata\ABOUT.md
copy con nist\ABOUT.md
copy con NoS\ABOUT.md
copy con onboarding\ABOUT.md
copy con overlays\ABOUT.md
copy con packages\ABOUT.md
copy con papers\ABOUT.md
copy con papers\bold_problems\ABOUT.md
copy con Paradoxes_canon\ABOUT.md
copy con projects\ABOUT.md
copy con public_support\ABOUT.md
copy con quantum-substrate-model\ABOUT.md
copy con regime_blindness_checklist\ABOUT.md
copy con registry\ABOUT.md
copy con Resilience_Checker\ABOUT.md
copy con resonance\ABOUT.md
copy con resonance-substrate-model\ABOUT.md
copy con resonance_atlas\ABOUT.md
copy con rfc\ABOUT.md
copy con RTT\ABOUT.md
copy con RTT\codex\ABOUT.md
copy con RTT\micro_core\ABOUT.md
copy con RTT\RTT-Inside\ABOUT.md
copy con RTT\RTT_12\ABOUT.md
copy con rtt-sdk\ABOUT.md
copy con rttcodes\ABOUT.md
copy con rtt_app\ABOUT.md
copy con rtt_store\ABOUT.md
copy con schemas\ABOUT.md
copy con scientific_instrument_review\ABOUT.md
copy con spacetime_micro_agent_validations\ABOUT.md
copy con spacetime_validation_and_regime_invariant_dimensional_cores\ABOUT.md
copy con spectral_clarity\ABOUT.md
copy con spectrum_standards_reviewed\ABOUT.md
copy con structural_life_regime_profiles\ABOUT.md
copy con structuring_mathematics\ABOUT.md
copy con substrate\ABOUT.md
copy con substrate_communications\ABOUT.md
copy con substrate_exposure_assay\ABOUT.md
copy con substrate_mind_science\ABOUT.md
copy con substrate_mind_science\analyzer\ABOUT.md
copy con TFT_3Pack_v1.3\ABOUT.md
copy con Triadic\ABOUT.md
copy con triadic_coordination_substrate\ABOUT.md
copy con triadic_observer_layer\ABOUT.md
copy con unified_resonance\ABOUT.md
copy con validation\ABOUT.md
copy con validators\ABOUT.md
copy con vst_for_embedding_stores_vector_databases\ABOUT.md
copy con vst_for_generative_models\ABOUT.md
copy con vst_for_large_language_models\ABOUT.md
copy con vst_for_multi_model_alignment\ABOUT.md
copy con vst_for_protein_language_models\ABOUT.md
copy con vst_for_robotics_and_control_policies\ABOUT.md
copy con vst_for_scientific_simulators\ABOUT.md
copy con workflows\ABOUT.md
copy con _ideas\ABOUT.md
copy con _template\ABOUT.md