@echo off
echo Removing 121 ABOUT.md's
del ai\ABOUT.md /Q
del ai-drift-calibration\ABOUT.md /Q
del AI_Resonance_Seed\ABOUT.md /Q
del alphafold_substrate_alignments\ABOUT.md /Q
del api\rtt\ABOUT.md /Q
del archive_experiments\engine\ABOUT.md /Q
del arrival_substrate_model\ABOUT.md /Q
del assets\ABOUT.md /Q
del atomic_clocks\ABOUT.md /Q
del audio_industry_reviewed\ABOUT.md /Q
del badges\ABOUT.md /Q
del boson-substrate-model\ABOUT.md /Q
del bridges\ABOUT.md /Q
del charts\ABOUT.md /Q
del clients\ABOUT.md /Q
del Coeus\ABOUT.md /Q
del configs\ABOUT.md /Q
del consciousness_substrate_model\ABOUT.md /Q
del contributors\ABOUT.md /Q
del corpus\ABOUT.md /Q
del curriculum\ABOUT.md /Q
del data\ABOUT.md /Q
del dimensional_substrate_regime_scanning_protocol\ABOUT.md /Q
del dimensional_substrate_structures\ABOUT.md /Q
del domain_tool_primers\ABOUT.md /Q
del ecoechosystem\ABOUT.md /Q
del education\ABOUT.md /Q
del education\alignment\ABOUT.md /Q
del education\animals\ABOUT.md /Q
del education\astrology\ABOUT.md /Q
del education\awareness\ABOUT.md /Q
del education\BRA\ABOUT.md /Q
del education\CivRegimeStack\ABOUT.md /Q
del education\ebooks\ABOUT.md /Q
del education\equations\ABOUT.md /Q
del education\peira\ABOUT.md /Q
del education\polisci\ABOUT.md /Q
del education\QnA_Atlas\ABOUT.md /Q
del education\subjects\ABOUT.md /Q
del education\translations\ABOUT.md /Q
del energy\ABOUT.md /Q
del enterprise_structural_awareness\ABOUT.md /Q
del facilities\ABOUT.md /Q
del feedback\ABOUT.md /Q
del gallery\ABOUT.md /Q
del global_energy_regime_awareness\ABOUT.md /Q
del glyphic_resonance\ABOUT.md /Q
del glyphs\ABOUT.md /Q
del governance\ABOUT.md /Q
del Governance_Substrate_Model\ABOUT.md /Q
del Governance_Substrate_Model\Analyzer\ABOUT.md /Q
del honor_roll\ABOUT.md /Q
del Inverted_Economics\ABOUT.md /Q
del inverted_star_ontology\ABOUT.md /Q
del labs\ABOUT.md /Q
del lactos\ABOUT.md /Q
del legal\ABOUT.md /Q
del library\ABOUT.md /Q
del Low_Dimensional_Structures\ABOUT.md /Q
del manufacturing_substrate_regime_model\ABOUT.md /Q
del media_substrate_model\ABOUT.md /Q
del media_substrate_model\analyzer\ABOUT.md /Q
del metadata\ABOUT.md /Q
del nist\ABOUT.md /Q
del NoS\ABOUT.md /Q
del onboarding\ABOUT.md /Q
del overlays\ABOUT.md /Q
del packages\ABOUT.md /Q
del papers\ABOUT.md /Q
del papers\bold_problems\ABOUT.md /Q
del Paradoxes_canon\ABOUT.md /Q
del projects\ABOUT.md /Q
del public_support\ABOUT.md /Q
del quantum-substrate-model\ABOUT.md /Q
del regime_blindness_checklist\ABOUT.md /Q
del registry\ABOUT.md /Q
del Resilience_Checker\ABOUT.md /Q
del resonance\ABOUT.md /Q
del resonance-substrate-model\ABOUT.md /Q
del resonance_atlas\ABOUT.md /Q
del rfc\ABOUT.md /Q
del RTT\ABOUT.md /Q
del RTT\codex\ABOUT.md /Q
del RTT\micro_core\ABOUT.md /Q
del RTT\RTT-Inside\ABOUT.md /Q
del RTT\RTT_12\ABOUT.md /Q
del rtt-sdk\ABOUT.md /Q
del rttcodes\ABOUT.md /Q
del rtt_app\ABOUT.md /Q
del rtt_store\ABOUT.md /Q
del schemas\ABOUT.md /Q
del scientific_instrument_review\ABOUT.md /Q
del spacetime_micro_agent_validations\ABOUT.md /Q
del spacetime_validation_and_regime_invariant_dimensional_cores\ABOUT.md /Q
del spectral_clarity\ABOUT.md /Q
del spectrum_standards_reviewed\ABOUT.md /Q
del structural_life_regime_profiles\ABOUT.md /Q
del structuring_mathematics\ABOUT.md /Q
del substrate\ABOUT.md /Q
del substrate_communications\ABOUT.md /Q
del substrate_exposure_assay\ABOUT.md /Q
del substrate_mind_science\ABOUT.md /Q
del substrate_mind_science\analyzer\ABOUT.md /Q
del TFT_3Pack_v1.3\ABOUT.md /Q
del Triadic\ABOUT.md /Q
del triadic_coordination_substrate\ABOUT.md /Q
del triadic_observer_layer\ABOUT.md /Q
del unified_resonance\ABOUT.md /Q
del validation\ABOUT.md /Q
del validators\ABOUT.md /Q
del vst_for_embedding_stores_vector_databases\ABOUT.md /Q
del vst_for_generative_models\ABOUT.md /Q
del vst_for_large_language_models\ABOUT.md /Q
del vst_for_multi_model_alignment\ABOUT.md /Q
del vst_for_protein_language_models\ABOUT.md /Q
del vst_for_robotics_and_control_policies\ABOUT.md /Q
del vst_for_scientific_simulators\ABOUT.md /Q
del workflows\ABOUT.md /Q
del _ideas\ABOUT.md /Q
del _template\ABOUT.md /Q