name: Validate README
permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  validate_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: Set Up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests beautifulsoup4

      - name: Run README Validator
        run: python docs/validators/readme_validator.py
